import DashboardLayout from "@/components/DashboardLayout";
import { MemberPage } from "@/components/MemberPage";
import { MonthlyReportDownload } from "@/components/MonthlyReportDownload";
import { CommunityOperations } from "@/components/CommunityOperations";
import { ExperienceOverview } from "@/components/ExperienceOverview";
import { ChurchBrandingForm } from "@/components/ChurchBrandingForm";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { useActiveChurch } from "@/hooks/useActiveChurch";
import { useAuth } from "@/_core/hooks/useAuth";
import { optimizeImage } from "@/lib/imageOptimization";
import { trpc } from "@/lib/trpc";
import { BarChart3, BookOpenText, Church, HeartHandshake, Image, Plus, QrCode, UsersRound } from "lucide-react";
import { QRCodeSVG } from "qrcode.react";
import { useState } from "react";
import { toast } from "sonner";

const stats = [{ key: "members", label: "Pessoas", icon: UsersRound }, { key: "bibleParticipants", label: "Plano Bíblico", icon: BookOpenText }, { key: "ebdPresent", label: "Presenças EBD", icon: Church }, { key: "activePrayers", label: "Pedidos ativos", icon: HeartHandshake }];

export default function Admin() {
  const { user } = useAuth(); const { church, isLoading } = useActiveChurch(); const role = church && "role" in church ? church.role : user?.role; const isManager = !church || role === "administrator"; const dashboard = trpc.admin.dashboard.useQuery({ churchId: church?.id ?? 0 }, { enabled: !!church && isManager }); const classes = trpc.ebd.classes.useQuery({ churchId: church?.id ?? 0 }, { enabled: !!church && isManager }); const [newChurch, setNewChurch] = useState({ name: "", slug: "" }); const [post, setPost] = useState({ title: "", body: "", type: "reflection" as const }); const [className, setClassName] = useState(""); const [lessonTitle, setLessonTitle] = useState(""); const [selectedClassId, setSelectedClassId] = useState(0); const [qrValue, setQrValue] = useState(""); const [albumTitle, setAlbumTitle] = useState(""); const [activeAlbumId, setActiveAlbumId] = useState(0); const [uploading, setUploading] = useState(false); const utils = trpc.useUtils();
  const createChurch = trpc.church.create.useMutation({ onSuccess: () => { toast.success("Igreja criada."); utils.church.mine.invalidate(); }, onError: e => toast.error(e.message) });
  const createPost = trpc.content.create.useMutation({ onSuccess: () => { toast.success("Conteúdo publicado."); setPost({ title: "", body: "", type: "reflection" }); }, onError: e => toast.error(e.message) });
  const createClass = trpc.management.createEbdClass.useMutation({ onSuccess: () => { toast.success("Classe criada."); setClassName(""); classes.refetch(); }, onError: e => toast.error(e.message) });
  const createLesson = trpc.management.createEbdLesson.useMutation({ onSuccess: data => { const base = window.location.origin; setQrValue(`${base}/ebd/check-in?token=${data.checkInToken}`); toast.success("QR Code de check-in criado."); }, onError: e => toast.error(e.message) });
  const createAlbum = trpc.community.createAlbum.useMutation({ onSuccess: data => { setActiveAlbumId(data.id); setAlbumTitle(""); toast.success("Álbum criado. Pode enviar fotos otimizadas."); }, onError: e => toast.error(e.message) });
  const uploadPhoto = trpc.community.uploadPhoto.useMutation({ onError: e => toast.error(e.message) });
  const uploadFiles = async (files: FileList | null) => { if (!church || !activeAlbumId || !files?.length) return; setUploading(true); try { for (const file of Array.from(files)) { const optimized = await optimizeImage(file); await uploadPhoto.mutateAsync({ churchId: church.id, albumId: activeAlbumId, filename: file.name, mimeType: "image/webp", dataBase64: optimized.webpDataUrl, thumbnailDataBase64: optimized.thumbnailDataUrl, originalBytes: optimized.originalBytes, width: optimized.width, height: optimized.height }); } toast.success("Fotos otimizadas e enviadas para a galeria."); } catch (error) { toast.error(error instanceof Error ? error.message : "Não foi possível enviar as fotos."); } finally { setUploading(false); } };
  if (church && !isManager) return <MemberPage><section className="mx-auto max-w-xl rounded-3xl border border-stone-200 bg-white p-8 text-center"><p className="eyebrow">Acesso restrito</p><h1 className="heading-display mt-2">Esta área é destinada ao Administrador</h1><p className="mt-3 text-sm leading-6 text-stone-600">Pastores acompanham o cuidado e as métricas numa área própria. Membros não acedem às operações da igreja.</p><a href="/pastor" className="mt-6 inline-flex text-sm font-semibold text-[#387266] underline-offset-4 hover:underline">Ir para a área pastoral →</a></section></MemberPage>;
  return <DashboardLayout><div className="mx-auto max-w-6xl pb-12"><section className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Gestão da Igreja</p><h1 className="heading-display">{church?.name ?? "A sua comunidade"}</h1><p className="mt-2 text-sm text-stone-600">Dados reais, comunicação com propósito e acesso controlado.</p>{church && "memberLimit" in church && <p className="mt-2 text-xs font-semibold text-[#417468]">Plano {church.planTier} · {dashboard.data?.members ?? 0} membros registados na faixa de {church.memberLimit}.</p>}</div>{church ? <MonthlyReportDownload churchId={church.id} /> : <span className="inline-flex items-center gap-2 text-xs font-medium text-stone-500"><BarChart3 className="size-4" />Atualização em tempo real</span>}</section>
  {isLoading ? <p className="text-sm text-stone-500">A carregar a gestão da igreja...</p> : !church ? <section className="max-w-xl rounded-3xl border border-stone-200 bg-white p-6"><h2 className="font-serif text-2xl font-semibold">Crie a sua igreja</h2><p className="mt-2 text-sm text-stone-600">Cada igreja utiliza uma experiência independente e os seus dados permanecem isolados dentro da infraestrutura partilhada.</p><div className="mt-5 grid gap-3"><Input value={newChurch.name} onChange={e => setNewChurch(current => ({ ...current, name: e.target.value }))} placeholder="Nome da igreja" /><Input value={newChurch.slug} onChange={e => setNewChurch(current => ({ ...current, slug: e.target.value.toLowerCase().replace(/\s+/g, "-") }))} placeholder="identificador-da-igreja" /><Button disabled={newChurch.name.length < 3 || newChurch.slug.length < 3 || createChurch.isPending} onClick={() => createChurch.mutate({ ...newChurch, timezone: "America/Sao_Paulo" })} className="bg-[#123d36] hover:bg-[#185047]">Criar igreja</Button></div></section> : <>
    <nav aria-label="Secções da administração" className="sticky top-2 z-20 mb-6 flex gap-2 overflow-x-auto rounded-2xl border border-stone-200 bg-[#fbfaf7]/95 p-2 backdrop-blur"><a href="#overview" className="whitespace-nowrap rounded-xl bg-[#123d36] px-3 py-2 text-xs font-semibold text-white">Visão geral</a><a href="#people" className="whitespace-nowrap rounded-xl px-3 py-2 text-xs font-semibold text-stone-600 hover:bg-stone-100">Pessoas</a><a href="#content" className="whitespace-nowrap rounded-xl px-3 py-2 text-xs font-semibold text-stone-600 hover:bg-stone-100">Conteúdo</a><a href="#agenda" className="whitespace-nowrap rounded-xl px-3 py-2 text-xs font-semibold text-stone-600 hover:bg-stone-100">Agenda e EBD</a><a href="#media" className="whitespace-nowrap rounded-xl px-3 py-2 text-xs font-semibold text-stone-600 hover:bg-stone-100">Mídia</a><a href="#reports" className="whitespace-nowrap rounded-xl px-3 py-2 text-xs font-semibold text-stone-600 hover:bg-stone-100">Relatórios</a></nav>
    <section id="overview" className="mb-7 rounded-3xl border border-[#cfe0d7] bg-[#edf5f0] p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Para fazer agora</p><h2 className="font-serif text-2xl font-semibold">Visão geral da operação</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-stone-600">Comece pelas pendências e aceda às tarefas mais frequentes em poucos passos.</p></div><span className="text-xs font-semibold text-[#417468]">Atualizado com os dados da igreja</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><a href="#people" className="rounded-2xl border border-[#cfe0d7] bg-white p-4"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-stone-400">Acompanhar</p><p className="mt-2 font-serif text-2xl font-semibold">{dashboard.data?.pastoralSignals ?? 0}</p><p className="text-sm text-stone-600">sinais objetivos</p></a><a href="#content" className="rounded-2xl border border-[#cfe0d7] bg-white p-4"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-stone-400">Comunicar</p><p className="mt-2 font-serif text-2xl font-semibold">{dashboard.data?.activePrayers ?? 0}</p><p className="text-sm text-stone-600">pedidos ativos</p></a><a href="#agenda" className="rounded-2xl border border-[#cfe0d7] bg-white p-4"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-stone-400">Organizar</p><p className="mt-2 font-serif text-2xl font-semibold">{classes.data?.length ?? 0}</p><p className="text-sm text-stone-600">turmas EBD</p></a><a href="#reports" className="rounded-2xl border border-[#cfe0d7] bg-white p-4"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-stone-400">Consultar</p><p className="mt-2 font-serif text-2xl font-semibold">{dashboard.data?.members ?? 0}</p><p className="text-sm text-stone-600">pessoas registadas</p></a></div></section>
    <section id="overview-stats" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{stats.map(stat => { const Icon = stat.icon; const value = dashboard.data?.[stat.key as keyof typeof dashboard.data] ?? 0; return <article key={stat.key} className="rounded-2xl border border-stone-200 bg-white p-5 shadow-[0_8px_30px_rgb(68,58,42,0.06)]"><Icon className="size-5 text-[#387266]" /><p className="mt-6 text-xs font-semibold uppercase tracking-[0.13em] text-stone-400">{stat.label}</p><p className="mt-1 font-serif text-3xl font-semibold">{value}</p></article>; })}</section>
    <section id="church" className="scroll-mt-24">{"primaryColor" in church && <ChurchBrandingForm church={church} />}</section>
    <section id="content" className="scroll-mt-24 mt-7 grid gap-5 lg:grid-cols-[1.15fr_0.85fr]"><article className="rounded-3xl border border-stone-200 bg-white p-6"><div className="flex items-start justify-between"><div><p className="eyebrow">CMS da Igreja</p><h2 className="font-serif text-2xl font-semibold">Publicar conteúdo</h2></div><span className="grid size-10 place-items-center rounded-2xl bg-[#e4f0e9] text-[#216154]"><Plus className="size-5" /></span></div><div className="mt-5 grid gap-3"><Input value={post.title} onChange={event => setPost(current => ({ ...current, title: event.target.value }))} placeholder="Título" /><Textarea value={post.body} onChange={event => setPost(current => ({ ...current, body: event.target.value }))} placeholder="Escreva uma reflexão, estudo ou palavra pastoral..." className="min-h-36" /><div className="flex flex-col justify-between gap-3 sm:flex-row"><select value={post.type} onChange={event => setPost(current => ({ ...current, type: event.target.value as typeof post.type }))} className="rounded-md border border-stone-200 bg-white px-3 py-2 text-sm"><option value="reflection">Reflexão</option><option value="devotional">Devocional</option><option value="study">Estudo</option><option value="pastoral_word">Palavra pastoral</option></select><Button disabled={post.title.length < 3 || post.body.length < 3 || createPost.isPending} onClick={() => createPost.mutate({ churchId: church.id, title: post.title, body: post.body, type: post.type, audience: "church", status: "published" })} className="bg-[#123d36] hover:bg-[#185047]">Publicar agora</Button></div></div></article><article className="rounded-3xl bg-[#123d36] p-6 text-[#f8f1df]"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#e8bd68]">Visão da comunidade</p><h2 className="mt-2 font-serif text-2xl font-semibold">Atividade nas últimas 4 semanas</h2><p className="mt-5 font-serif text-5xl font-semibold text-[#e8bd68]">{dashboard.data?.weeklyActivity ?? 0}</p><p className="mt-2 text-sm leading-6 text-white/65">Membros que registaram uma ação significativa. Este indicador é calculado a partir das atividades persistidas.</p><div className="mt-6 border-t border-white/10 pt-5 text-sm text-white/75"><div className="flex justify-between"><span>Sinais objetivos de atenção</span><strong className="text-[#e8bd68]">{dashboard.data?.pastoralSignals ?? 0}</strong></div><p className="mt-2 text-xs leading-5 text-white/45">A interpretação e qualquer acompanhamento permanecem sempre humanos e privados.</p></div></article></section>
    <section id="agenda" className="scroll-mt-24 mt-7 grid gap-5 lg:grid-cols-[1.15fr_0.85fr]"><article className="rounded-3xl border border-stone-200 bg-white p-6"><div className="flex items-start justify-between"><div><p className="eyebrow">EBD</p><h2 className="font-serif text-2xl font-semibold">Classes e check-in</h2></div><span className="grid size-10 place-items-center rounded-2xl bg-[#e4f0e9] text-[#216154]"><Church className="size-5" /></span></div><div className="mt-5 flex gap-2"><Input value={className} onChange={event => setClassName(event.target.value)} placeholder="Nome da nova classe" /><Button disabled={className.length < 3 || createClass.isPending} onClick={() => createClass.mutate({ churchId: church.id, name: className })} variant="outline">Criar classe</Button></div><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_auto]"><select value={selectedClassId || classes.data?.[0]?.id || ""} onChange={event => setSelectedClassId(Number(event.target.value))} className="rounded-md border border-stone-200 bg-white px-3 py-2 text-sm"><option value="">Selecione uma classe</option>{classes.data?.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><Input value={lessonTitle} onChange={event => setLessonTitle(event.target.value)} placeholder="Título da aula" /></div><Button disabled={!lessonTitle || !(selectedClassId || classes.data?.[0]?.id) || createLesson.isPending} onClick={() => createLesson.mutate({ churchId: church.id, classId: selectedClassId || classes.data?.[0]?.id || 0, title: lessonTitle, scheduledAt: new Date() })} className="mt-3 bg-[#123d36] hover:bg-[#185047]"><QrCode className="mr-2 size-4" />Gerar QR Code</Button></article><article className="rounded-3xl border border-[#cfe0d7] bg-[#edf5f0] p-6 text-center"><p className="eyebrow">Check-in da aula</p>{qrValue ? <><div className="mx-auto mt-4 grid size-44 place-items-center rounded-2xl bg-white p-3"><QRCodeSVG value={qrValue} size={150} /></div><p className="mt-4 text-sm text-[#417468]">Os alunos escaneiam este código para registar uma presença.</p></> : <div className="grid min-h-44 place-items-center text-sm leading-6 text-stone-500">Ainda não há QR Code. Crie uma aula e ele aparecerá aqui para partilhar com a turma.</div>}</article></section>
    <section id="people" className="scroll-mt-24"><CommunityOperations churchId={church.id} /></section>
    <section id="reports" className="scroll-mt-24"><ExperienceOverview churchId={church.id} /></section>
    <section id="media" className="scroll-mt-24 mt-7 grid gap-5 lg:grid-cols-[1.15fr_0.85fr]"><article className="rounded-3xl border border-stone-200 bg-white p-6"><div className="flex items-start justify-between"><div><p className="eyebrow">Galeria</p><h2 className="font-serif text-2xl font-semibold">Álbuns e fotografias</h2></div><Image className="size-5 text-[#b78535]" /></div><div className="mt-5 flex gap-2"><Input value={albumTitle} onChange={event => setAlbumTitle(event.target.value)} placeholder="Título do álbum" /><Button disabled={albumTitle.length < 3 || createAlbum.isPending} onClick={() => createAlbum.mutate({ churchId: church.id, title: albumTitle })} variant="outline">Criar álbum</Button></div><div className="mt-4 rounded-2xl border border-dashed border-[#bcd4c8] bg-[#edf5f0] p-4"><label className="block text-sm font-medium text-[#216154]">Enviar fotografias otimizadas<input className="mt-3 block w-full text-xs text-stone-600 file:mr-3 file:rounded-md file:border-0 file:bg-[#123d36] file:px-3 file:py-2 file:text-xs file:font-semibold file:text-white" type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={!activeAlbumId || uploading} onChange={event => uploadFiles(event.target.files)} /></label><p className="mt-3 text-xs leading-5 text-stone-500">As fotos são convertidas para WebP, limitadas a 2048 px e recebem miniatura de 480 px antes do envio.</p>{!activeAlbumId && <p className="mt-2 text-xs font-medium text-[#a4762e]">Para começar, crie um álbum e depois selecione as imagens a enviar.</p>}</div></article><article className="rounded-3xl border border-stone-200 bg-white p-6"><Church className="size-5 text-[#387266]" /><h3 className="mt-4 font-serif text-xl font-semibold">EBD</h3><p className="mt-1 text-sm text-stone-600">Classes, aulas, QR Code e frequência.</p><UsersRound className="mt-8 size-5 text-[#aa6161]" /><h3 className="mt-4 font-serif text-xl font-semibold">Conexões</h3><p className="mt-1 text-sm text-stone-600">Moderação de profissionais e negócios da comunidade.</p></article></section>
  </>}</div></DashboardLayout>;
}
