import { MemberPage } from "@/components/MemberPage";
import { Button } from "@/components/ui/button";
import { useActiveChurch } from "@/hooks/useActiveChurch";
import { trpc } from "@/lib/trpc";
import { Bell, ChevronRight } from "lucide-react";
import { useState } from "react";

export default function Announcements() {
  const { church } = useActiveChurch(); const notices = trpc.community.announcements.useQuery({ churchId: church?.id ?? 0 }, { enabled: !!church }); const [selectedId, setSelectedId] = useState<number | null>(null); const selected = notices.data?.find(item => item.id === selectedId);
  return <MemberPage><section className="mb-8"><p className="eyebrow">Comunidade</p><h1 className="heading-display">Avisos</h1><p className="mt-2 max-w-xl text-stone-600">Comunicações publicadas pela sua igreja para acompanhar com clareza.</p></section>{selected ? <article className="rounded-3xl border border-stone-200 bg-white p-6"><Button variant="ghost" className="-ml-3 text-[#387266]" onClick={() => setSelectedId(null)}>← Todos os avisos</Button>{selected.imageUrl && <img src={selected.imageUrl} alt="" className="mt-4 h-52 w-full rounded-2xl object-cover" />}<p className="mt-5 text-xs font-semibold uppercase tracking-[0.15em] text-stone-400">{selected.publishedAt ? new Date(selected.publishedAt).toLocaleDateString("pt-PT", { day: "2-digit", month: "long", year: "numeric" }) : "Aviso da igreja"}</p><h2 className="mt-2 font-serif text-3xl font-semibold">{selected.title}</h2><p className="mt-5 whitespace-pre-wrap text-sm leading-7 text-stone-700">{selected.content}</p></article> : notices.isLoading ? <p className="text-sm text-stone-500">A carregar avisos...</p> : notices.data?.length ? <div className="grid gap-3">{notices.data.map(notice => <button key={notice.id} onClick={() => setSelectedId(notice.id)} className="flex items-center gap-4 rounded-2xl border border-stone-200 bg-white p-5 text-left shadow-[0_8px_30px_rgb(68,58,42,0.06)]"><span className="grid size-10 shrink-0 place-items-center rounded-2xl bg-[#e4f0e9] text-[#216154]"><Bell className="size-5" /></span><span className="min-w-0 flex-1"><span className="block font-serif text-xl font-semibold">{notice.title}</span><span className="mt-1 block truncate text-sm text-stone-600">{notice.content}</span></span><ChevronRight className="size-5 text-stone-400" /></button>)}</div> : <div className="rounded-2xl border border-dashed border-stone-300 bg-white/60 p-8 text-center text-sm text-stone-500">Ainda não existem avisos publicados para esta igreja.</div>}</MemberPage>;
}
