import { MemberPage } from "@/components/MemberPage";
import { Button } from "@/components/ui/button";
import { useActiveChurch } from "@/hooks/useActiveChurch";
import { trpc } from "@/lib/trpc";
import { BookOpenText, ExternalLink } from "lucide-react";
import { useState } from "react";

export default function Ebd() {
  const { church } = useActiveChurch(); const magazines = trpc.ebd.magazines.useQuery({ churchId: church?.id ?? 0 }, { enabled: !!church }); const [selected, setSelected] = useState<number | null>(null); const lessons = trpc.ebd.magazineLessons.useQuery({ churchId: church?.id ?? 0, magazineId: selected ?? 0 }, { enabled: !!church && !!selected });
  return <MemberPage><section className="mb-8"><p className="eyebrow">Formação</p><h1 className="heading-display">Revista EBD</h1><p className="mt-2 max-w-xl text-stone-600">Lições e materiais publicados pela sua igreja, abertos apenas quando precisar.</p></section>{!selected ? <div className="grid gap-4 md:grid-cols-2">{magazines.data?.map(magazine => <button key={magazine.id} onClick={() => setSelected(magazine.id)} className="rounded-3xl border border-stone-200 bg-white p-6 text-left shadow-[0_8px_30px_rgb(68,58,42,0.06)]"><BookOpenText className="size-5 text-[#b78535]" /><p className="mt-5 text-xs font-semibold uppercase tracking-[0.15em] text-stone-400">{magazine.trimesterLabel}</p><h2 className="mt-1 font-serif text-2xl font-semibold">{magazine.theme}</h2><p className="mt-2 text-sm leading-6 text-stone-600">{magazine.description ?? "Ver lições da revista."}</p></button>)}{!magazines.isLoading && !magazines.data?.length && <div className="rounded-2xl border border-dashed border-stone-300 bg-white/60 p-8 text-center text-sm text-stone-500">Ainda não existem revistas EBD publicadas.</div>}</div> : <section><Button variant="ghost" onClick={() => setSelected(null)} className="-ml-3 text-[#387266]">← Revistas</Button><div className="mt-3 grid gap-3">{lessons.data?.map(lesson => <article key={lesson.id} className="rounded-2xl border border-stone-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-stone-400">Lição {lesson.lessonNumber}</p><h2 className="mt-1 font-serif text-xl font-semibold">{lesson.title}</h2><p className="mt-2 text-sm leading-6 text-stone-600">{lesson.description ?? "Material de apoio disponível nesta lição."}</p>{lesson.materialUrl && <a href={lesson.materialUrl} target="_blank" rel="noreferrer" className="mt-4 inline-flex"><Button variant="outline"><ExternalLink className="mr-2 size-4" />Abrir material</Button></a>}</article>)}</div></section>}</MemberPage>;
}
