import { MemberPage } from "@/components/MemberPage";
import { Button } from "@/components/ui/button";
import { useActiveChurch } from "@/hooks/useActiveChurch";
import { trpc } from "@/lib/trpc";
import { Download, Images, Share2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function Gallery() {
  const { church } = useActiveChurch(); const albums = trpc.community.albums.useQuery({ churchId: church?.id ?? 0 }, { enabled: !!church }); const [selected, setSelected] = useState<number | null>(null); const photos = trpc.community.albumPhotos.useQuery({ churchId: church?.id ?? 0, albumId: selected ?? 0 }, { enabled: !!church && !!selected });
  const share = async (title: string, url: string) => { if (navigator.share) await navigator.share({ title, url }); else { await navigator.clipboard.writeText(url); toast.success("Ligação copiada."); } };
  return <MemberPage><section className="mb-8"><p className="eyebrow">Comunidade</p><h1 className="heading-display">Galeria da igreja</h1><p className="mt-2 max-w-xl text-stone-600">Momentos guardados para celebrar a vida em comunidade.</p></section>{!selected ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{albums.data?.map(album => <button key={album.id} onClick={() => setSelected(album.id)} className="overflow-hidden rounded-3xl border border-stone-200 bg-white text-left shadow-[0_8px_30px_rgb(68,58,42,0.06)] transition-transform hover:-translate-y-1"><div className="grid aspect-[4/3] place-items-center bg-[#e4f0e9] text-[#387266]">{album.coverPhotoUrl ? <img src={album.coverPhotoUrl} alt="" className="size-full object-cover" /> : <Images className="size-9" />}</div><div className="p-5"><p className="font-serif text-xl font-semibold">{album.title}</p><p className="mt-1 line-clamp-2 text-sm text-stone-600">{album.description ?? "Ver fotografias do álbum."}</p></div></button>)}{!albums.isLoading && !albums.data?.length && <div className="col-span-full rounded-2xl border border-dashed border-stone-300 bg-white/60 p-8 text-center text-sm text-stone-500">Ainda não existem álbuns publicados.</div>}</div> : <section><div className="mb-5 flex items-center justify-between"><div><Button variant="ghost" onClick={() => setSelected(null)} className="-ml-3 text-[#387266]">← Álbuns</Button><h2 className="font-serif text-2xl font-semibold">{photos.data?.[0]?.albumTitle ?? "Álbum"}</h2></div></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4">{photos.data?.map(photo => <figure key={photo.id} className="group overflow-hidden rounded-2xl border border-stone-200 bg-white"><img src={photo.url} alt={photo.caption ?? photo.title ?? "Fotografia da igreja"} className="aspect-square w-full object-cover" /><figcaption className="p-3"><p className="truncate text-xs text-stone-600">{photo.caption ?? photo.title ?? photo.filename}</p><div className="mt-2 flex gap-1">{photo.allowDownloads && <a href={photo.url} download={photo.filename} className="grid size-7 place-items-center rounded-md bg-stone-100 text-stone-600" aria-label="Descarregar foto"><Download className="size-3.5" /></a>}<button onClick={() => share(photo.title ?? photo.filename, photo.url)} className="grid size-7 place-items-center rounded-md bg-stone-100 text-stone-600" aria-label="Partilhar foto"><Share2 className="size-3.5" /></button></div></figcaption></figure>)}</div></section>}</MemberPage>;
}
