import { MemberPage } from "@/components/MemberPage";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { useActiveChurch } from "@/hooks/useActiveChurch";
import { trpc } from "@/lib/trpc";
import { startLogin } from "@/const";
import { useAuth } from "@/_core/hooks/useAuth";
import { ArrowRight, BookOpen, CalendarDays, Check, Flame, HeartHandshake, Sparkles, SunMedium } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";

function Welcome() {
  return <div className="grid min-h-screen place-items-center bg-[#123d36] p-5"><section className="w-full max-w-md rounded-[2rem] border border-white/10 bg-white/[0.06] p-8 text-center text-[#f8f1df] shadow-2xl backdrop-blur"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-[#e8bd68] text-[#153a33]"><Sparkles className="size-6" /></span><p className="mt-7 text-xs font-semibold uppercase tracking-[0.2em] text-[#e8bd68]">Igreja Jornada</p><h1 className="mt-3 font-serif text-4xl font-semibold leading-tight">A sua comunidade, todos os dias.</h1><p className="mx-auto mt-4 max-w-sm text-sm leading-6 text-white/65">Palavra, constância, participação e cuidado num único lugar.</p><Button onClick={() => startLogin()} className="mt-7 h-11 w-full bg-[#e8bd68] text-[#153a33] hover:bg-[#f2ce84]">Entrar na Jornada</Button><a href="/landing.html" className="mt-4 block text-sm text-white/70 underline-offset-4 hover:text-white hover:underline">Conhecer o CONGREGA</a></section></div>;
}

export default function Home() {
  const { user, loading } = useAuth(); const { church, isLoading: churchLoading } = useActiveChurch(); const home = trpc.member.home.useQuery({ churchId: church?.id ?? 0 }, { enabled: !!church }); const utils = trpc.useUtils();
  const complete = trpc.bible.complete.useMutation({ onSuccess: () => { toast.success("Leitura concluída. Que a Palavra continue a acompanhar o seu dia."); utils.member.home.invalidate(); }, onError: error => toast.error(error.message) });
  if (loading) return <div className="grid min-h-screen place-items-center bg-[#f7f5f0] text-sm text-stone-500">A preparar a sua Jornada...</div>;
  if (!user) return <Welcome />;
  if (churchLoading) return <div className="grid min-h-screen place-items-center bg-[#f7f5f0] text-sm text-stone-500">A ligar à sua igreja...</div>;
  if (!church) return <MemberPage><section className="mx-auto max-w-xl rounded-3xl border border-stone-200 bg-white p-8 text-center"><p className="eyebrow">Bem-vindo à Jornada</p><h1 className="heading-display mt-2">Ainda não pertence a uma igreja</h1><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-stone-600">Peça à liderança da sua igreja para o convidar para a comunidade.</p></section></MemberPage>;
  const data = home.data; const readingPercent = data?.progress.total ? Math.round((data.progress.completed / data.progress.total) * 100) : 0;
  return <MemberPage><section className="mb-8 flex items-end justify-between gap-4"><div><p className="eyebrow">{church.name}</p><h1 className="heading-display">Olá, {user.name?.split(" ")[0] ?? "amigo"}.</h1><p className="mt-2 text-sm text-stone-600">Um passo de cada vez, com propósito.</p></div><span className="hidden size-12 place-items-center rounded-2xl bg-[#e6efe9] text-[#216154] md:grid"><Sparkles className="size-5" /></span></section>
    {home.isLoading ? <div className="rounded-3xl border border-stone-200 bg-white p-8 text-sm text-stone-500">A organizar o seu dia...</div> : <>
      <section className="overflow-hidden rounded-3xl bg-[#123d36] p-5 text-[#f8f1df] shadow-[0_18px_45px_rgba(18,61,54,0.18)] md:p-7"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#e8bd68]">A sua jornada hoje</p><h2 className="mt-2 font-serif text-2xl font-semibold">{data?.reading?.reference ?? "Plano Bíblico"}</h2><p className="mt-2 text-sm text-white/65">{data?.reading ? `Dia ${data.reading.dayNumber} do seu caminho de leitura.` : "Escolha ou aguarde a publicação do Plano Bíblico da igreja."}</p></div><span className="grid size-10 place-items-center rounded-2xl bg-white/10"><BookOpen className="size-5 text-[#e8bd68]" /></span></div><div className="mt-6"><div className="mb-2 flex justify-between text-xs text-white/60"><span>{data?.progress.completed ?? 0} leituras concluídas</span><span>{readingPercent}%</span></div><Progress value={readingPercent} className="h-1.5 bg-white/15 [&>div]:bg-[#e8bd68]" /></div><Button disabled={!data?.reading || complete.isPending} onClick={() => data?.reading && complete.mutate({ churchId: church.id, readingId: data.reading.id })} className="mt-6 w-full bg-[#e8bd68] text-[#153a33] hover:bg-[#f2ce84]"><Check className="mr-2 size-4" />{data?.progress.isComplete ? "Leitura concluída" : "Marcar como concluído"}</Button></section>
      <section className="mt-5 grid gap-4 md:grid-cols-[1.35fr_1fr]"><article className="rounded-3xl border border-stone-200 bg-white p-5 shadow-[0_8px_30px_rgb(68,58,42,0.06)]"><div className="flex items-center justify-between"><span className="grid size-10 place-items-center rounded-2xl bg-[#fbefcf] text-[#a4762e]"><SunMedium className="size-5" /></span><Link href="/devocional" className="text-xs font-semibold text-[#387266] hover:underline">Ler devocional</Link></div><p className="mt-5 text-xs font-semibold uppercase tracking-[0.15em] text-stone-400">Devocional Diário</p><h2 className="mt-1 font-serif text-xl font-semibold">{data?.devotional?.title ?? "Em breve"}</h2><p className="mt-2 text-sm leading-6 text-stone-600">{data?.devotional?.reflection?.slice(0, 170) ?? "A reflexão diária será publicada pela sua igreja."}{data?.devotional?.reflection && "..."}</p></article><article className="rounded-3xl border border-[#cfe0d7] bg-[#edf5f0] p-5"><span className="grid size-10 place-items-center rounded-2xl bg-white text-[#216154]"><Flame className="size-5" /></span><p className="mt-5 text-xs font-semibold uppercase tracking-[0.15em] text-[#5c8b7e]">A sua sequência</p><p className="mt-1 font-serif text-4xl font-semibold text-[#16483f]">{data?.progress.streak ?? 0}<span className="ml-1 text-base font-medium">dias</span></p><p className="mt-2 text-sm text-[#417468]">A constância cresce com cada pequeno passo.</p></article></section>
      <section className="mt-8"><div className="mb-4 flex items-center justify-between"><div><p className="eyebrow">Hoje na sua igreja</p><h2 className="font-serif text-2xl font-semibold">Esta semana</h2></div><Link href="/agenda" className="text-sm font-semibold text-[#387266]">Agenda completa</Link></div><div className="grid gap-3 md:grid-cols-3"><Link href="/agenda" className="group rounded-2xl border border-stone-200 bg-white p-4 transition-transform hover:-translate-y-0.5"><CalendarDays className="size-5 text-[#b78535]" /><p className="mt-4 text-xs font-semibold uppercase tracking-[0.13em] text-stone-400">Próximo encontro</p><p className="mt-1 font-serif text-lg font-semibold">{data?.upcoming[0]?.title ?? "Acompanhe a agenda"}</p><p className="mt-1 text-xs text-stone-500">{data?.upcoming[0] ? new Date(data.upcoming[0].startsAt).toLocaleString("pt-PT", { weekday: "short", day: "2-digit", hour: "2-digit", minute: "2-digit" }) : "Sem eventos próximos"}</p></Link><Link href="/oracao" className="group rounded-2xl border border-stone-200 bg-white p-4 transition-transform hover:-translate-y-0.5"><HeartHandshake className="size-5 text-[#aa6161]" /><p className="mt-4 text-xs font-semibold uppercase tracking-[0.13em] text-stone-400">Cuidado</p><p className="mt-1 font-serif text-lg font-semibold">Pedido de oração</p><p className="mt-1 text-xs text-stone-500">Partilhe com a privacidade que escolher.</p></Link><Link href="/jornada" className="group rounded-2xl border border-stone-200 bg-white p-4 transition-transform hover:-translate-y-0.5"><ArrowRight className="size-5 text-[#387266]" /><p className="mt-4 text-xs font-semibold uppercase tracking-[0.13em] text-stone-400">Jornada</p><p className="mt-1 font-serif text-lg font-semibold">{data?.milestones ?? 0} Marcos</p><p className="mt-1 text-xs text-stone-500">Celebre o caminho, sem competição.</p></Link></div></section>
      {!!data?.notices?.length && <section className="mt-8 rounded-3xl border border-[#eadfbe] bg-[#fffaf0] p-5"><div className="mb-4 flex items-center justify-between gap-3"><div><p className="eyebrow text-[#a4762e]">Importante</p><h2 className="font-serif text-2xl font-semibold">Avisos da igreja</h2></div><Link href="/avisos" className="text-sm font-semibold text-[#a4762e]">Ver todos</Link></div><div className="grid gap-3 md:grid-cols-3">{data.notices.slice(0, 3).map(notice => <Link key={notice.id} href="/avisos" className="rounded-2xl border border-[#eadfbe] bg-white/70 p-4 transition-colors hover:bg-white"><p className="font-serif text-lg font-semibold">{notice.title}</p><p className="mt-2 line-clamp-2 text-sm leading-6 text-stone-600">{notice.content}</p></Link>)}</div></section>}
    </>}</MemberPage>;
}
