import { MemberPage } from "@/components/MemberPage";
import { Progress } from "@/components/ui/progress";
import { useActiveChurch } from "@/hooks/useActiveChurch";
import { trpc } from "@/lib/trpc";
import { ExperienceFeedback } from "@/components/ExperienceFeedback";
import { Award, BookOpen, CalendarCheck2, Flame } from "lucide-react";

export default function Journey() {
  const { church } = useActiveChurch(); const home = trpc.member.home.useQuery({ churchId: church?.id ?? 0 }, { enabled: !!church }); const data = home.data; const progress = data?.progress.total ? Math.round((data.progress.completed / data.progress.total) * 100) : 0;
  return <MemberPage><section className="mb-8"><p className="eyebrow">Minha Jornada</p><h1 className="heading-display">Crescimento com constância</h1><p className="mt-2 max-w-xl text-stone-600">Um retrato gentil do seu caminho, sem comparações e sem pressão.</p></section>
    <div className="grid gap-4 md:grid-cols-2"><article className="rounded-3xl bg-[#123d36] p-6 text-[#f8f1df]"><BookOpen className="size-5 text-[#e8bd68]" /><p className="mt-5 text-xs font-semibold uppercase tracking-[0.16em] text-[#e8bd68]">Plano Bíblico</p><p className="mt-2 font-serif text-4xl font-semibold">{data?.progress.completed ?? 0}<span className="ml-1 text-base font-medium text-white/60">/ {data?.progress.total ?? 365}</span></p><div className="mt-5"><div className="mb-2 flex justify-between text-xs text-white/60"><span>O seu progresso</span><span>{progress}%</span></div><Progress value={progress} className="h-1.5 bg-white/15 [&>div]:bg-[#e8bd68]" /></div></article><article className="rounded-3xl border border-[#cfe0d7] bg-[#edf5f0] p-6"><Flame className="size-5 text-[#b78535]" /><p className="mt-5 text-xs font-semibold uppercase tracking-[0.16em] text-[#5c8b7e]">Sequência de leitura</p><p className="mt-2 font-serif text-4xl font-semibold text-[#16483f]">{data?.progress.streak ?? 0}<span className="ml-1 text-base font-medium text-[#417468]">dias</span></p><p className="mt-4 text-sm leading-6 text-[#417468]">Cada dia conta. Recomeçar também é parte da jornada.</p></article></div>
    <section className="mt-6 grid gap-4 md:grid-cols-2"><article className="rounded-3xl border border-stone-200 bg-white p-6"><CalendarCheck2 className="size-5 text-[#387266]" /><p className="mt-5 text-xs font-semibold uppercase tracking-[0.16em] text-stone-400">EBD</p><h2 className="mt-2 font-serif text-2xl font-semibold">Acompanhe as suas aulas</h2><p className="mt-2 text-sm leading-6 text-stone-600">A frequência é registada nas aulas em que está inscrito. O histórico aparece aqui assim que houver aulas realizadas.</p></article><article className="rounded-3xl border border-stone-200 bg-white p-6"><Award className="size-5 text-[#b78535]" /><p className="mt-5 text-xs font-semibold uppercase tracking-[0.16em] text-stone-400">Marcos</p><h2 className="mt-2 font-serif text-4xl font-semibold">{data?.milestones ?? 0}</h2><p className="mt-2 text-sm leading-6 text-stone-600">Conquistas desbloqueadas pela sua participação e constância.</p></article></section>{church && <ExperienceFeedback churchId={church.id} />}</MemberPage>;
}
