import { MemberPage } from "@/components/MemberPage";
import { MonthlyReportDownload } from "@/components/MonthlyReportDownload";
import { useActiveChurch } from "@/hooks/useActiveChurch";
import { trpc } from "@/lib/trpc";
import { BarChart3, BookOpenText, HeartHandshake, UsersRound } from "lucide-react";

export default function Pastor() {
  const { church } = useActiveChurch(); const role = church && "role" in church ? church.role : "member"; const dashboard = trpc.admin.dashboard.useQuery({ churchId: church?.id ?? 0 }, { enabled: !!church && role === "pastor" }); const signals = trpc.care.pastoralSignals.useQuery({ churchId: church?.id ?? 0 }, { enabled: !!church && role === "pastor" }); const prayers = trpc.care.leadershipPrayers.useQuery({ churchId: church?.id ?? 0 }, { enabled: !!church && role === "pastor" });
  if (!church || role !== "pastor") return <MemberPage><section className="mx-auto max-w-xl rounded-3xl border border-stone-200 bg-white p-8 text-center"><p className="eyebrow">Acesso restrito</p><h1 className="heading-display mt-2">Área pastoral</h1><p className="mt-3 text-sm leading-6 text-stone-600">Esta área é exclusiva do perfil de Pastor e apresenta somente indicadores objetivos para apoiar o cuidado humano.</p></section></MemberPage>;
  const cards = [{ label: "Membros ativos", value: dashboard.data?.weeklyActivity ?? 0, icon: UsersRound }, { label: "Leituras concluídas", value: dashboard.data?.bibleReadingsCompleted ?? 0, icon: BookOpenText }, { label: "Presenças EBD", value: dashboard.data?.ebdPresent ?? 0, icon: UsersRound }, { label: "Pedidos ativos", value: dashboard.data?.activePrayers ?? 0, icon: HeartHandshake }];
  return <MemberPage><section className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Acompanhamento pastoral</p><h1 className="heading-display">Cuidar com discernimento</h1><p className="mt-2 max-w-xl text-sm leading-6 text-stone-600">Os indicadores mostram factos de participação. A escuta, interpretação e ação permanecem humanas.</p></div><MonthlyReportDownload churchId={church.id} /></section><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{cards.map(card => { const Icon = card.icon; return <article key={card.label} className="rounded-2xl border border-stone-200 bg-white p-5"><Icon className="size-5 text-[#387266]" /><p className="mt-5 text-xs font-semibold uppercase tracking-[0.13em] text-stone-400">{card.label}</p><p className="mt-1 font-serif text-3xl font-semibold">{card.value}</p></article>; })}</div><section className="mt-7 rounded-3xl bg-[#123d36] p-6 text-[#f8f1df]"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-2xl bg-white/10"><BarChart3 className="size-5 text-[#e8bd68]" /></span><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#e8bd68]">Atenção pastoral</p><h2 className="mt-1 font-serif text-2xl font-semibold">Sinais objetivos de participação</h2><p className="mt-2 text-sm text-white/65">Um sinal aponta um dado para atenção; não descreve causa, condição ou diagnóstico.</p></div></div><div className="mt-6 grid gap-3">{signals.data?.length ? signals.data.map(signal => <article key={signal.id} className="rounded-2xl border border-white/10 bg-white/[0.06] p-4"><div className="flex justify-between gap-4"><p className="font-medium">{signal.memberName ?? "Membro"}</p><span className="text-xs text-[#e8bd68]">{signal.signalType.replaceAll("_", " ")}</span></div><p className="mt-2 text-sm leading-6 text-white/70">{signal.observation}</p></article>) : <p className="rounded-2xl border border-dashed border-white/15 p-5 text-sm text-white/65">Nenhum sinal objetivo aberto neste momento.</p>}</div></section><section className="mt-7 rounded-3xl border border-stone-200 bg-white p-6"><p className="eyebrow">Cuidado</p><h2 className="mt-1 font-serif text-2xl font-semibold">Pedidos de oração autorizados</h2><div className="mt-5 grid gap-3">{prayers.data?.length ? prayers.data.map(prayer => <article key={prayer.id} className="rounded-2xl bg-[#f7f5f0] p-4"><div className="flex justify-between gap-3 text-xs font-semibold uppercase tracking-[0.12em] text-stone-400"><span>{prayer.visibility.replaceAll("_", " ")}</span><span>{prayer.status.replaceAll("_", " ")}</span></div><p className="mt-3 text-sm leading-6 text-stone-700">{prayer.content}</p></article>) : <p className="rounded-2xl border border-dashed border-stone-300 p-5 text-sm text-stone-500">Não existem pedidos de oração autorizados no momento.</p>}</div></section></MemberPage>;
}
