import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Palette } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

type Branding = { id: number; name: string; logoUrl: string | null; primaryColor: string; secondaryColor: string; coverImageUrl: string | null; welcomeMessage: string | null };

export function ChurchBrandingForm({ church }: { church: Branding }) {
  const [form, setForm] = useState({ name: church.name, logoUrl: church.logoUrl ?? "", primaryColor: church.primaryColor, secondaryColor: church.secondaryColor, coverImageUrl: church.coverImageUrl ?? "", welcomeMessage: church.welcomeMessage ?? "" }); const utils = trpc.useUtils();
  useEffect(() => setForm({ name: church.name, logoUrl: church.logoUrl ?? "", primaryColor: church.primaryColor, secondaryColor: church.secondaryColor, coverImageUrl: church.coverImageUrl ?? "", welcomeMessage: church.welcomeMessage ?? "" }), [church]);
  const update = trpc.church.updateBranding.useMutation({ onSuccess: () => { utils.church.mine.invalidate(); toast.success("Identidade visual atualizada para esta igreja."); }, onError: error => toast.error(error.message) });
  return <section className="mt-7 rounded-3xl border border-stone-200 bg-white p-6"><div className="flex items-start gap-3"><span className="grid size-10 place-items-center rounded-2xl" style={{ backgroundColor: form.primaryColor, color: form.secondaryColor }}><Palette className="size-5" /></span><div><p className="eyebrow">Identidade visual</p><h2 className="font-serif text-2xl font-semibold">A sua igreja na Jornada</h2><p className="mt-1 text-sm text-stone-600">Esta configuração é aplicada apenas aos membros desta igreja. O ícone técnico da PWA permanece único.</p></div></div><div className="mt-6 grid gap-4 md:grid-cols-2"><Input value={form.name} onChange={event => setForm(current => ({ ...current, name: event.target.value }))} placeholder="Nome da igreja" /><Input value={form.logoUrl} onChange={event => setForm(current => ({ ...current, logoUrl: event.target.value }))} placeholder="URL do logo (opcional)" /><label className="flex items-center gap-3 rounded-md border border-stone-200 px-3 py-2 text-sm"><input type="color" value={form.primaryColor} onChange={event => setForm(current => ({ ...current, primaryColor: event.target.value }))} />Cor primária</label><label className="flex items-center gap-3 rounded-md border border-stone-200 px-3 py-2 text-sm"><input type="color" value={form.secondaryColor} onChange={event => setForm(current => ({ ...current, secondaryColor: event.target.value }))} />Cor secundária</label><Input value={form.coverImageUrl} onChange={event => setForm(current => ({ ...current, coverImageUrl: event.target.value }))} placeholder="URL da imagem de capa (opcional)" className="md:col-span-2" /><Input value={form.welcomeMessage} onChange={event => setForm(current => ({ ...current, welcomeMessage: event.target.value }))} placeholder="Mensagem de boas-vindas (opcional)" className="md:col-span-2" /></div><div className="mt-5 flex items-center justify-between rounded-2xl p-4" style={{ backgroundColor: form.primaryColor, color: "white" }}><p className="font-serif text-lg">{form.welcomeMessage || `Bem-vindo à ${form.name}`}</p><Button disabled={form.name.length < 3 || update.isPending} onClick={() => update.mutate({ churchId: church.id, name: form.name, logoUrl: form.logoUrl || undefined, primaryColor: form.primaryColor, secondaryColor: form.secondaryColor, coverImageUrl: form.coverImageUrl || undefined, welcomeMessage: form.welcomeMessage || undefined })} style={{ backgroundColor: form.secondaryColor, color: form.primaryColor }}>Guardar identidade</Button></div></section>;
}
