import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CalendarPlus, Megaphone } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export function CommunityOperations({ churchId }: { churchId: number }) {
  const [event, setEvent] = useState({ title: "", when: "", location: "" }); const [announcement, setAnnouncement] = useState({ title: "", content: "" });
  const createEvent = trpc.management.createEvent.useMutation({ onSuccess: () => { setEvent({ title: "", when: "", location: "" }); toast.success("Evento publicado no calendário."); }, onError: error => toast.error(error.message) });
  const createAnnouncement = trpc.management.createAnnouncement.useMutation({ onSuccess: () => { setAnnouncement({ title: "", content: "" }); toast.success("Aviso publicado."); }, onError: error => toast.error(error.message) });
  return <section className="mt-7 grid gap-5 lg:grid-cols-2"><article className="rounded-3xl border border-stone-200 bg-white p-6"><CalendarPlus className="size-5 text-[#387266]" /><p className="mt-4 text-xs font-semibold uppercase tracking-[0.16em] text-stone-400">Agenda</p><h2 className="mt-1 font-serif text-2xl font-semibold">Publicar evento</h2><div className="mt-5 grid gap-3"><Input value={event.title} onChange={item => setEvent(current => ({ ...current, title: item.target.value }))} placeholder="Título do evento" /><Input type="datetime-local" value={event.when} onChange={item => setEvent(current => ({ ...current, when: item.target.value }))} /><Input value={event.location} onChange={item => setEvent(current => ({ ...current, location: item.target.value }))} placeholder="Local (opcional)" /><Button disabled={!event.title || !event.when || createEvent.isPending} onClick={() => createEvent.mutate({ churchId, title: event.title, location: event.location || undefined, startsAt: new Date(event.when), status: "published" })} className="bg-[#123d36] hover:bg-[#185047]">Publicar evento</Button></div></article><article className="rounded-3xl border border-stone-200 bg-white p-6"><Megaphone className="size-5 text-[#b78535]" /><p className="mt-4 text-xs font-semibold uppercase tracking-[0.16em] text-stone-400">Comunicação</p><h2 className="mt-1 font-serif text-2xl font-semibold">Publicar aviso</h2><div className="mt-5 grid gap-3"><Input value={announcement.title} onChange={item => setAnnouncement(current => ({ ...current, title: item.target.value }))} placeholder="Título do aviso" /><Textarea value={announcement.content} onChange={item => setAnnouncement(current => ({ ...current, content: item.target.value }))} placeholder="Mensagem para a comunidade" className="min-h-24" /><Button disabled={announcement.title.length < 3 || announcement.content.length < 5 || createAnnouncement.isPending} onClick={() => createAnnouncement.mutate({ churchId, ...announcement, status: "published" })} variant="outline">Publicar aviso</Button></div></article></section>;
}
